
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint_0_position_controller:
    type: effort_controllers/JointPositionController
    joint:  rotor_unit_0_revolutejoint
    pid: {p: 2.0, i: 0.001, d: 0.1}
  joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint:  rotor_unit_1_revolutejoint
    pid: {p: 2.0, i: 0.001, d: 0.1}
  joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint:  rotor_unit_2_revolutejoint
    pid: {p: 2.0, i: 0.001, d: 0.1}
  joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint:  rotor_unit_3_revolutejoint
    pid: {p: 2.0, i: 0.001, d: 0.1}
  joint_4_position_controller:
    type: effort_controllers/JointPositionController
    joint:  rotor_unit_4_revolutejoint
    pid: {p: 2.0, i: 0.001, d: 0.1}
  joint_5_position_controller:
    type: effort_controllers/JointPositionController
    joint:  rotor_unit_5_revolutejoint
    pid: {p: 2.0, i: 0.001, d: 0.1}

  # joint2_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint2
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
